<?php

########################################################################
# Extension Manager/Repository config file for ext: "assets"
#
# Auto generated by Extbase Kickstarter 2011-04-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Assets',
	'description' => 'List you assets/files from a Database or a Directory Structure, usable for galleries, file directories, image databases...',
	'category' => '',
	'author' => 'Thomas Allmer',
	'author_email' => 'at@delusionworld.com',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>